### ISSUE TITLE
Contributing: Correct command to regenerate ILParser.cs from ILParser.jay

### ISSUE THREAD

**Issue by ashmind** [kkokosa/Mobius.ILasm#7]
I've used Mono's `jay.exe` to regenerate `ILParser.cs` after some changes in `ILParser.jay`.
The commend I used was something like this (with `skeleton.cs` being Mono's [skeleton.cs](https://github.com/mono/mono/blob/main/mcs/jay/skeleton.cs)):
```
jay -c ILParser.jay < skeleton.cs > ILParser.cs
```
However, the output has a lot more differences than I expected, especially around whitespace.

Is there a canonical way to regenerate it within this repository?

**Comment by kkokosa** [comment]
Unfortunatelly not. My goal was to seed ILParser.cs by jay and just forget about it. In fact, I plan huge refactorings around ILParser.cs.

**Comment by ashmind** [comment]
Thanks! Sounds reasonable, though it might be useful to delete the jay file for clarity.

**Comment by kkokosa** [comment]
Yeah, I will make "Contributing" section clear about that.
